/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.Scanner;
import java.io.IOException;


import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpRequestFactory;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpResponseException;
import com.google.api.client.http.javanet.NetHttpTransport;



public class App {
    
    // 1. ファクトリーを作成（スレッドセーフ）
    static HttpRequestFactory fac
    = (new NetHttpTransport()).createRequestFactory();
 

    public static void main(String[] args) {
        
        System.out.println("URLを入力して下さい。");
        
        Scanner scan = new Scanner(System.in);
        String str = scan.next();
       
        HttpResponse res = null;
        try {
          // 2. リクエストの送信
          res = fac.buildGetRequest(
            new GenericUrl(str)
          ).execute();
          
          

          // 3. レスポンスの操作
          System.out.println(
            "Get response. [status=" + res.getStatusCode() + "]"
          );
          System.out.println(res.parseAsString());
        }
        catch (HttpResponseException e) {
          System.err.println(  // エラー発生時
            "Error. [staus=" + e.getStatusCode() + "]"
          );
          throw new RuntimeException(e);
        }
        catch (IOException e) {
          throw new RuntimeException(e);
        }
        finally {
          try { if (res != null) res.disconnect(); }
          catch (IOException e) {
            throw new RuntimeException(e);
          }
        }
      }





}