/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import org.junit.Test;
//import static org.junit.Assert.*;
import static org.assertj.core.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpRequestFactory;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.InputStreamContent;
import com.google.api.client.http.apache.ApacheHttpTransport;


//通信が通っているかどうかのテスト
public class AppTest {
 
    //通信が通っているかどうか(Get)
    @Test
    public void testGoogleHttpJavaClientGet() {
        HttpTransport transport = new ApacheHttpTransport();
        HttpRequestFactory factory = transport.createRequestFactory();

        GenericUrl url = new GenericUrl("http://www.google.com/get?param=value");

        try {
            HttpRequest request = factory.buildGetRequest(url);
            HttpResponse response = request.execute();

            try {
                assertThat(response.getStatusCode())
                    .isEqualTo(200);
                assertThat(response.parseAsString())
                    .contains("Accessed URL = /get?param=value",
                              "Accessed Method = GET");
            } finally {
                response.disconnect();
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                transport.shutdown();
            } catch (IOException e ) {
                e.printStackTrace();
            }
        }
    }

    //通信が通っているかどうか(Post)
    @Test
    public void testGoogleHttpJavaClientPost() {
        HttpTransport transport = new ApacheHttpTransport();
        HttpRequestFactory factory = transport.createRequestFactory();

        GenericUrl url = new GenericUrl("http://www.google.com/post");

        try {
            StringBuilder builder = new StringBuilder();
            builder.append("POST Body");
            builder.append("\r\n");
            builder.append("Hello Http Server!!");
            builder.append("\r\n");

            HttpRequest request =
                factory.buildPostRequest(url,
                                         new InputStreamContent("text/plain",
                                                                new ByteArrayInputStream(builder.toString().getBytes(StandardCharsets.UTF_8))));
            HttpResponse response = request.execute();

            try {
                assertThat(response.getStatusCode())
                    .isEqualTo(200);
                assertThat(response.parseAsString())
                    .contains("Accessed URL = /post",
                              "Accessed Method = POST",
                              "Request Body<<",
                              "POST Body",
                              "Hello Http Server!!",
                              ">>");
            } finally {
                response.disconnect();
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                transport.shutdown();
            } catch (IOException e ) {
                e.printStackTrace();
            }
        }
    }
    

}
