/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/*import com.google.api.client.http.ByteArrayContent;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpRequestFactory;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpResponseException;
import com.google.api.client.http.javanet.NetHttpTransport;*/

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.URL;
import java.net.HttpURLConnection;
import java.nio.charset.StandardCharsets;

public class App {
    
    // 1. ファクトリーを作成（スレッドセーフ）
    //static HttpRequestFactory fac
    //= (new NetHttpTransport()).createRequestFactory();
    static String str1;
    static String str2;
    static String str3;
    static Scanner scan1;
    static Scanner scan2;
    static Scanner scan3;

    public static void main(String[] args) {
        
      //コマンド入力
        System.out.println("コマンドを入力してください");
        scan1 = new Scanner(System.in);
        str1 = scan1.next();
        
      //URL入力
        System.out.println("URLを入力して下さい。");
         scan2 = new Scanner(System.in);
        str2 = scan2.next();

     
        if(str1.equals("g")){
          executeGet();
        }
        if(str1.equals("x")){
            executeFile();
        }
        if(str1.equals("h")){
            executeHeader();
        }
        if(str1.equals("p")){
          executePost();
        }
        if(str1.equals("pd")){
            System.out.println("パラメーターを入力して下さい。");
            scan3 = new Scanner(System.in);
            str3 = scan3.next();

            executePostd();
          }
             
           

      }

      private static void executeGet() {
        System.out.println("===== HTTP GET Start =====");
        try {
            URL url = new URL(str2);

            HttpURLConnection connection = null;

            try {
                connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("GET");

                if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    try (InputStreamReader isr = new InputStreamReader(connection.getInputStream(),
                                                                       StandardCharsets.UTF_8);
                         BufferedReader reader = new BufferedReader(isr)) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            System.out.println(line);
                        }
                    }
                }
            } finally {
                if (connection != null) {
                    connection.disconnect();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("===== HTTP GET End =====");
    }

    private static void executeFile() {
        System.out.println("===== HTTP GET Start =====");
        try {
            URL url = new URL(str2);

            HttpURLConnection connection = null;

            try {
                connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("GET");

                if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    try (InputStreamReader isr = new InputStreamReader(connection.getInputStream(),
                                                                       StandardCharsets.UTF_8);
                         BufferedReader reader = new BufferedReader(isr)) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            //System.out.println(line);
                            // FileWriterクラスのオブジェクトを生成する
                            FileWriter file = new FileWriter("str.txt");
                            // PrintWriterクラスのオブジェクトを生成する
                            PrintWriter pw = new PrintWriter(new BufferedWriter(file));
            
                            //ファイルに書き込む
                             pw.println(line);
            
            
                            //ファイルを閉じる
                            pw.close();
                        }
                    }
                }
            } finally {
                if (connection != null) {
                    connection.disconnect();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("===== HTTP GET End =====");
    }

    private static void executeHeader() {
        System.out.println("===== HTTP GET Start =====");
        try {

            URL obj = new URL(str2);
            HttpURLConnection conn = (HttpURLConnection) obj.openConnection();
            Map<String, List<String>> map = conn.getHeaderFields();
        
            System.out.println("Printing Response Header...\n");
        
            for (Map.Entry<String, List<String>> entry : map.entrySet()) {
                System.out.println( entry.getKey()
                                   + " : " + entry.getValue());
            }
        
            System.out.println("\nGet Response Header By Key ...\n");
            String server = conn.getHeaderField("Server");
        
            if (server == null) {
                System.out.println("Key 'Server' is not found!");
            } else {
                System.out.println("Server - " + server);
            }
        
            System.out.println("\n Done");
        
            } catch (Exception e) {
            e.printStackTrace();
            }

        System.out.println("===== HTTP GET End =====");
    }



    private static void executePost() {
        System.out.println("===== HTTP POST Start =====");
        try {
            URL url = new URL(str2);

            HttpURLConnection connection = null;

            try {
                connection = (HttpURLConnection) url.openConnection();
                connection.setDoOutput(true);
                connection.setRequestMethod("POST");

                BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(connection.getOutputStream(),
                                                                                  StandardCharsets.UTF_8));
               /* writer.write("POST Body");
                writer.write("\r\n");
                writer.write("Hello Http Server!!");
                writer.write("\r\n");
                writer.flush();*/

                if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    try (InputStreamReader isr = new InputStreamReader(connection.getInputStream(),
                                                                       StandardCharsets.UTF_8);
                         BufferedReader reader = new BufferedReader(isr)) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            System.out.println(line);
                        }
                    }
                }
            } finally {
                if (connection != null) {
                    connection.disconnect();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("===== HTTP POST End =====");
    }

    private static void executePostd() {
        System.out.println("===== HTTP POST Start =====");
        try {
            URL url = new URL(str2);

            HttpURLConnection connection = null;

            try {
                connection = (HttpURLConnection) url.openConnection();
                connection.setDoOutput(true);
                connection.setRequestMethod("POST");

                BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(connection.getOutputStream(),
                                                                                  StandardCharsets.UTF_8));
                writer.write(str3);
                writer.flush();

                if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    try (InputStreamReader isr = new InputStreamReader(connection.getInputStream(),
                                                                       StandardCharsets.UTF_8);
                         BufferedReader reader = new BufferedReader(isr)) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            System.out.println(line);
                        }
                    }
                }
            } finally {
                if (connection != null) {
                    connection.disconnect();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("===== HTTP POST End =====");
    }


}